#!/usr/bin/env python3

import signal
import sys
import os
import OPi.GPIO as GPIO
import time

import socket
import sys
import json

HOST, PORT = "127.0.0.1", 7000

preset = 0
preset_name = ['pedal_low', 'pedal_middle', 'pedal_hi']

OVER = 21

def signal_handler(sig, frame):
    GPIO.cleanup()
    sys.exit(0)

if __name__ == '__main__':
    GPIO.setmode(GPIO.BCM)

    GPIO.setup(OVER, GPIO.IN, pull_up_down=GPIO.PUD_UP)

    while True:

        if GPIO.input(OVER) == GPIO.LOW:
            if (preset < 2):
                preset += 1
            else:
                preset = 0
            data = '{"jsonrpc": "2.0","method": "setpreset","params": ["my","'+preset_name[preset]+'"]}^M'+"\n"
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                # Connect to server and send data
                sock.connect((HOST, PORT))
                sock.sendall(bytes(data,encoding="utf-8"))
                sock.close()
            except Exception:
                pass

            time.sleep(2)
        else:
            time.sleep(0.1)

    signal.signal(signal.SIGINT, signal_handler)
    signal.pause()
